declare module 'decompress-tar'
declare module 'decompress-tarbz2'
declare module 'decompress-targz'
declare module 'decompress-unzip'
declare module 'decompress-bzip2'
declare module 'decompress-gz'
declare module 'file-type'
