name: Parallel Multi-OS App Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] #[ubuntu-latest, windows-latest, macos-latest]
        app: [act]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17'

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install deps
        run: pnpm i

      - name: Install gobot
        run: npm i -g gobot
          gobot --g-version

      - name: Test ${{ matrix.app }}
        run: pnpm plop test "gobot" --no-progress
